### ISSUE TITLE
simple SETNX example

### ISSUE THREAD

**Issue by patrikx3** [microfleet/ioredis-lock#11]
hi!
thanks for helping.
just asking, i just need to create a new session id, like uuid. it says this is the simple use case, but i dont get it. what do i do with the lock? i just want to add a new unique id if it doesn't exist , how do i do it?

thanks so much!
ciao!

**Comment by AVVS** [comment]
you dont need a lock to create an id - check docs at https://redis.io/commands/set

**Comment by patrikx3** [comment]
thanks so much. got it. ciao!
