### ISSUE TITLE
Does not work on Node 4.x

### ISSUE THREAD

**Issue by aabrams** [microfleet/ioredis-lock#5]
Uses es6 syntax not available on 4.x

**Comment by AVVS** [comment]
yep, no longer supported. you can install earlier versions with support for it

**Comment by aabrams** [comment]
OK, using 2.x for now. thanks!

**Comment by behrad** [comment]
I'm also locked to 2.x cause of using node v4
Can you update to the latest ioredis for 2.x @AVVS ?

**Comment by AVVS** [comment]
yes, I'll make a separate branch for this

**Comment by behrad** [comment]
Great @AVVS  waiting for this...

another issue is you are defining ioredis 1.x in peerDependencies! That's locking my module to use ioredis 2.x! Ain't it better to add it to optionalDependencies or simply dependencies?

Or even upgrade to ioredis 2.x version dependency.

**Comment by bkw** [comment]
node v4 support now has a PR in #8

**Comment by AVVS** [comment]
Fixed thanks to @bkw, version is published under `@legacy` tag in npm, do `npm i ioredis-lock@legacy -S` to get it, mentioned this on the master README and added an extra note regarding branch where it is developed
