### ISSUE TITLE
getAcquiredLocks() does not take timeout into account

### ISSUE THREAD

**Issue by aabrams** [microfleet/ioredis-lock#6]
I created a lock with a timeout of 3000 milis. Does that not mean the lock should be released automatically after 3 seconds? If so, why does it show indefinitely in the acquiredLocks list?

**Comment by AVVS** [comment]
it wont be released automatically, however, notion of this lock in the database will be lost (based on ttl). You should either call extend or release. In the latter case it will fail after 3s
